# Generated by Django 3.1.1 on 2020-10-16 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('movie_image', models.ImageField(blank=True, upload_to='movie_images')),
                ('movie', models.FileField(null=True, upload_to='')),
                ('description', models.TextField(null=True)),
                ('author', models.CharField(max_length=200)),
                ('date_released', models.DateTimeField(verbose_name=django.utils.timezone.now)),
                ('favorites', models.ManyToManyField(blank=True, related_name='movie_favorites', to=settings.AUTH_USER_MODEL)),
                ('genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movie_genre', to='main.genres')),
                ('likes', models.ManyToManyField(blank=True, related_name='movie_like', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
