# Generated by Django 3.1.1 on 2020-10-16 12:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='date_released',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
