# Generated by Django 3.1.1 on 2020-10-16 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201016_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='movie',
        ),
    ]
