# Generated by Django 3.1.1 on 2020-10-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_movies_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='movie',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
