# Generated by Django 3.1.1 on 2020-10-16 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_movies_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='movie',
            field=models.FileField(blank=True, upload_to='movie_path'),
        ),
    ]
