# Generated by Django 3.1.1 on 2021-01-02 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_auto_20201016_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tv_shows_episodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('Tv_show_image', models.ImageField(blank=True, upload_to='movie_images')),
                ('Tv_show_path', models.FileField(blank=True, upload_to='movie_path')),
                ('episode_description', models.TextField(null=True)),
                ('author', models.CharField(max_length=200)),
                ('date_released', models.DateTimeField(default=django.utils.timezone.now)),
                ('favorites', models.ManyToManyField(blank=True, related_name='tv_show_favorites', to=settings.AUTH_USER_MODEL)),
                ('genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Tv_shows_episodes', to='main.genres')),
                ('likes', models.ManyToManyField(blank=True, related_name='tv_show_like', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tv_shows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_released', models.DateTimeField(default=django.utils.timezone.now)),
                ('Tv_shows_description', models.TextField(null=True)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.genres')),
            ],
        ),
    ]
