# Generated by Django 3.1.1 on 2021-01-02 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_tv_shows_tv_shows_episodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tv_shows',
            name='tv_show_image',
            field=models.ImageField(blank=True, upload_to='tv_shows_images'),
        ),
    ]
