# Generated by Django 3.1.1 on 2021-01-02 18:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_tv_shows_tv_show_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tv_shows_seasons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tv_show_image', models.ImageField(blank=True, upload_to='tv_shows_seasons_images')),
                ('date_released', models.DateTimeField(default=django.utils.timezone.now)),
                ('Tv_shows_description', models.TextField(null=True)),
                ('tv_show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Tv_shows_seasons', to='main.tv_shows')),
            ],
        ),
        migrations.DeleteModel(
            name='Tv_shows_episodes',
        ),
    ]
