# Generated by Django 3.1.1 on 2021-01-04 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_tv_shows_episodes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tv_shows_episodes',
            name='author',
        ),
    ]
