# Generated by Django 3.1.1 on 2021-01-04 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_tv_shows_episodes_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tv_shows_episodes',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Tv_shows_episodes_genre', to='main.genres'),
        ),
        migrations.AlterField(
            model_name='tv_shows_episodes',
            name='tv_show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Tv_shows_episodes', to='main.tv_shows_seasons'),
        ),
    ]
