# Generated by Django 3.1.1 on 2021-01-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210104_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='tv_shows_episodes',
            name='reference_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
