# Generated by Django 3.1.1 on 2021-01-04 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_tv_shows_episodes_reference_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tv_shows_seasons',
            name='reference_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
