# Generated by Django 3.1.1 on 2021-01-17 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_tv_shows_seasons_reference_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='popular_tv_shows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tv_show_genre', to='main.genres')),
                ('tv_show', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tv_show', to='main.tv_shows')),
            ],
        ),
        migrations.CreateModel(
            name='Popular_movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='popula_movie_genre', to='main.genres')),
                ('movie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movie', to='main.genres')),
            ],
        ),
    ]
