# Generated by Django 3.1.1 on 2021-01-17 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_popular_movies_popular_tv_shows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popular_movies',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='popular_movie', to='main.movies'),
        ),
    ]
