# Generated by Django 3.1.1 on 2021-01-12 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
